# Regenerates assets/estate/estate-map.json from cadastre_grid.json, a
# pre-classified 92x92 grid (WATER/BUILDING/LAND/...) extracted from the
# property's cadastral "Plan de Situation" PDF -- see cadastre_grid.json's
# accompanying "meta" block for the pixel<->world (RGF93CC48) transform used
# to build it. Assumes assets/estate/tileset.png already contains the
# compact tile layout referenced below (tid() offsets); that tileset is
# composited by hand from the ChaoticCherryCake source sheet and isn't
# regenerated by this script.
#
# cadastre_grid.json is deliberately NOT committed (see ../../.gitignore): it
# carries the property's real survey coordinates. Recover it, and the aerial /
# cadastre reference images, from mirrorsky commit 737923c:
#   git -C ../../../mirrorsky show 737923c:tools/estate-map/cadastre_grid.json
import json
import math
from collections import deque

COLS_SHEET = 8  # compact tileset: 8 cols x 6 rows

def tid(col, row):
    return row * COLS_SHEET + col

GRASS = tid(0, 0)
WATER = tid(1, 0)
POOL = tid(2, 0)
PATH = tid(3, 0)
TENNIS = tid(4, 0)
ROOF_FILL = tid(5, 0)
GRASS_ALT = tid(6, 0)
BUSH_A = tid(7, 0)
BUSH_B = tid(0, 1)
TREE = tid(1, 1)
TREE2 = tid(2, 1)
FLOWER = tid(3, 1)

BUILDING = [[tid(c, 2 + r) for c in range(3)] for r in range(4)]

import os
_HERE = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(_HERE, 'cadastre_grid.json')) as f:
    d = json.load(f)
cad = d['grid']
meta = d['meta']
GRID_W, GRID_H = meta['COLS'], meta['ROWS']
XMIN, XMAX, YMIN, YMAX, TILE_M = meta['XMIN'], meta['XMAX'], meta['YMIN'], meta['YMAX'], meta['TILE_M']

# cadastre_grid.json is pre-rotated (see ROTATION_NOTE in its meta) so that the
# house/pool/paths -- which sit at a real ~49 degree angle to true north -- come
# out axis-aligned in this grid, matching the orientation the estate was hand-tiled
# against in map-builder.html. world_to_grid() therefore does the original
# real-world-meters -> unrotated-grid lookup, then applies that same rotation
# (K, Offset, padX/padY, all baked in at grid-generation time) to land in this
# grid's actual coordinate frame.
PAD_X, PAD_Y = meta['padX'], meta['padY']
K = complex(meta['K_re'], meta['K_im'])
OFFSET = complex(meta['Offset_re'], meta['Offset_im'])

def world_to_grid(X, Y):
    old_c, old_r = (X - XMIN) / TILE_M, (YMAX - Y) / TILE_M
    new_g = (complex(old_c, old_r) - OFFSET / 15.5) / K
    return (new_g.real + PAD_X, new_g.imag + PAD_Y)

# --- OpenStreetMap overlay -------------------------------------------------
# The cadastral plan only knows LAND / WATER / BUILDING, so paths and field
# boundaries used to be guessed. OSM carries real geometry for both. It also
# carries the *other* river channel: the cadastre captured the eastern arm and
# OSM the western one, and only their union closes the loop that makes the
# island an island.
import osm as _osm

_osm_data = _osm.fetch()
OSM = _osm.classify(_osm_data, meta, GRID_W, GRID_H)
print("osm:", {k: len(v) for k, v in sorted(OSM.items()) if v})

ground = [[GRASS for _ in range(GRID_W)] for _ in range(GRID_H)]
building = [[None for _ in range(GRID_W)] for _ in range(GRID_H)]

def fill(grid, x0, x1, y0, y1, tile):
    for y in range(y0, y1):
        for x in range(x0, x1):
            if 0 <= x < GRID_W and 0 <= y < GRID_H:
                grid[y][x] = tile

def stamp(grid, x0, y0, tiles):
    for ry, row_tiles in enumerate(tiles):
        for rx, t in enumerate(row_tiles):
            if 0 <= y0 + ry < GRID_H and 0 <= x0 + rx < GRID_W:
                grid[y0 + ry][x0 + rx] = t

# --- Water: straight from the cadastral classification (the real river shape) ---
WATER_CELLS = {(c, r) for r in range(GRID_H) for c in range(GRID_W)
               if cad[r][c] == 'WATER'} | OSM['water']
for (c, r) in WATER_CELLS:
    ground[r][c] = WATER

# --- Buildings: connected-component analysis on the real classified footprints ---
def find_components(target):
    seen = [[False] * GRID_W for _ in range(GRID_H)]
    comps = []
    for r in range(GRID_H):
        for c in range(GRID_W):
            if cad[r][c] == target and not seen[r][c]:
                q = deque([(r, c)])
                seen[r][c] = True
                cells = []
                while q:
                    cr, cc = q.popleft()
                    cells.append((cr, cc))
                    for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
                        nr, nc = cr + dr, cc + dc
                        if 0 <= nr < GRID_H and 0 <= nc < GRID_W and not seen[nr][nc] and cad[nr][nc] == target:
                            seen[nr][nc] = True
                            q.append((nr, nc))
                comps.append(cells)
    return comps

buildings = find_components('BUILDING')
buildings.sort(key=len, reverse=True)

def centroid(cells):
    rs = sum(c[0] for c in cells) / len(cells)
    cs = sum(c[1] for c in cells) / len(cells)
    return (rs, cs)

def bbox(cells):
    rs = [c[0] for c in cells]; cs = [c[1] for c in cells]
    return (min(rs), max(rs), min(cs), max(cs))

# Fill every real building footprint with the solid roof colour (accurate
# size/shape straight from the cadastral plan) and mark it for collision.
for comp in buildings:
    if len(comp) < 3:
        continue  # tiny noise specks
    for (r, c) in comp:
        ground[r][c] = ROOF_FILL

# cadastre_grid.json is now rotated to the estate's true orientation rather
# than true north (see world_to_grid() above), so "south"/"north" no longer
# line up with +row/-row the way they used to. Everything below identifies
# the house/pool-house/gatehouse and lays out paths using real spatial
# relationships (distance to water, distance to the house, the direction
# from the house toward the entrance) instead of hardcoded row/col ranges,
# so it stays correct regardless of how the grid is oriented.
water_cells = [(r, c) for (c, r) in WATER_CELLS]

# Multi-source BFS from every water cell gives exact grid-distance to the
# nearest water for every cell in one linear pass (used below for both
# building identification and the "wooded riverbank" decoration density).
dist_to_water = [[None] * GRID_W for _ in range(GRID_H)]
_q = deque()
for (r, c) in water_cells:
    dist_to_water[r][c] = 0
    _q.append((r, c))
while _q:
    r, c = _q.popleft()
    d = dist_to_water[r][c]
    for dr, dc in ((-1, 0), (1, 0), (0, -1), (0, 1)):
        nr, nc = r + dr, c + dc
        if 0 <= nr < GRID_H and 0 <= nc < GRID_W and dist_to_water[nr][nc] is None:
            dist_to_water[nr][nc] = d + 1
            _q.append((nr, nc))

# The main house and pool house (parcels 56/55) are the two significant
# building footprints closest to the river; the closer of the two -- it
# sits right on the riverbank -- is the main house.
sizable = [comp for comp in buildings if len(comp) >= 15]
sizable.sort(key=lambda comp: min(dist_to_water[r][c] for (r, c) in comp))
MAIN_HOUSE, POOL_HOUSE = (sizable + [None, None])[:2]

for comp in (MAIN_HOUSE, POOL_HOUSE):
    if not comp:
        continue
    r0, r1, c0, c1 = bbox(comp)
    cc = (c0 + c1) // 2
    stamp(building, max(0, cc - 1), r0, BUILDING)

house_cr, house_cc = centroid(MAIN_HOUSE) if MAIN_HOUSE else (GRID_H / 2, GRID_W / 2)

# --- Pool: a small rectangle beside the pool house footprint, offset along
# the pool house's own long axis rather than assuming it's axis-aligned ---
if POOL_HOUSE:
    pr0, pr1, pc0, pc1 = bbox(POOL_HOUSE)
    ph_cr, ph_cc = centroid(POOL_HOUSE)
    # direction away from the main house, through the pool house -- that's
    # the side the pool sits on
    away_r, away_c = ph_cr - house_cr, ph_cc - house_cc
    mag = math.hypot(away_r, away_c) or 1
    away_r, away_c = away_r / mag, away_c / mag
    pool_cr = int(ph_cr + away_r * 6)
    pool_cc = int(ph_cc + away_c * 6)
    pool_c0, pool_c1, pool_r0, pool_r1 = pool_cc - 2, pool_cc + 2, pool_cr - 1, pool_cr + 2
    fill(ground, pool_c0, pool_c1, pool_r0, pool_r1, POOL)
    # a one-tile poolside path all the way round, matching the hand-tiled
    # reference (the automated pool used to be a bare rectangle with nothing
    # around it)
    for r in range(pool_r0 - 1, pool_r1 + 1):
        for c in range(pool_c0 - 1, pool_c1 + 1):
            if not (0 <= r < GRID_H and 0 <= c < GRID_W):
                continue
            if pool_r0 <= r < pool_r1 and pool_c0 <= c < pool_c1:
                continue  # inside the pool itself
            if ground[r][c] == GRASS:
                ground[r][c] = PATH

# --- Tennis court: manually located on the cadastral plan (a dashed
# rectangle that doesn't classify by fill colour), centred in its bbox ---
tc0, tc1 = world_to_grid(1527400, 7228035)
tc2, tc3 = world_to_grid(1527450, 7227994)
tcx = int((tc0 + tc2) / 2); tcy = int((tc1 + tc3) / 2)
fill(ground, tcx - 6, tcx + 6, tcy - 4, tcy + 4, TENNIS)

# --- Driveway: from the road up to the main house's forecourt, routed past
# the small building near the entrance (likely a lodge/gatehouse). The
# gatehouse is simply the nearest other sizable building to the main house --
# a very robust signal regardless of grid orientation. ---
others = [comp for comp in sizable if comp is not MAIN_HOUSE and comp is not POOL_HOUSE]
gatehouse = min(others, key=lambda comp: math.hypot(centroid(comp)[0] - house_cr, centroid(comp)[1] - house_cc)) if others else None

if gatehouse:
    gate_cr, gate_cc = centroid(gatehouse)
else:
    gate_cr, gate_cc = house_cr + 20, house_cc + 15

# Direction from the house toward the entrance/road side -- this replaces
# the old assumption that the road is due south (+row) of the house.
drive_r, drive_c = gate_cr - house_cr, gate_cc - house_cc
_mag = math.hypot(drive_r, drive_c) or 1
drive_r, drive_c = drive_r / _mag, drive_c / _mag

if MAIN_HOUSE:
    hr0, hr1, hc0, hc1 = bbox(MAIN_HOUSE)
    house_edge_r = int(house_cr + drive_r * (hr1 - hr0 + 2) / 2 + drive_r * 2)
    house_edge_c = int(house_cc + drive_c * (hc1 - hc0 + 2) / 2 + drive_c * 2)
else:
    house_edge_r, house_edge_c = int(house_cr), int(house_cc)

def path_strip(cr, cc, half=0):
    # half=1 stamped a 4x3 block per step, which at 2.5 m/tile is a ten-metre
    # driveway -- it read as a desert cutting the map in half. A country drive
    # is two tiles wide.
    fill(ground, int(cc) - half - 1, int(cc) + half + 1, int(cr) - half, int(cr) + half + 1, PATH)

# forecourt immediately in front of the house
path_strip(house_edge_r, house_edge_c, half=1)

# path segment: house forecourt -> gatehouse
steps = max(1, int(_mag))
for i in range(steps + 1):
    t = i / steps
    r = house_edge_r + t * (gate_cr - house_edge_r)
    c = house_edge_c + t * (gate_cc - house_edge_c)
    path_strip(r, c)

# path segment: gatehouse -> map edge in the same direction (representing
# the driveway continuing on to reach the public road)
edge_r, edge_c = gate_cr, gate_cc
for _ in range(int(GRID_W + GRID_H)):
    edge_r += drive_r * 2
    edge_c += drive_c * 2
    if not (0 <= edge_r < GRID_H and 0 <= edge_c < GRID_W):
        break
    path_strip(edge_r, edge_c)

# a stretch of public road around where the driveway meets the grid edge
road_len = 24
perp_r, perp_c = -drive_c, drive_r  # perpendicular to the driveway direction
for i in range(-road_len, road_len):
    r = edge_r + perp_r * i
    c = edge_c + perp_c * i
    path_strip(r, c)

# --- Spawn point: at the road, just off the end of the driveway ---
spawn_tile_x = max(1, min(GRID_W - 2, int(edge_c - drive_c * 3)))
spawn_tile_y = max(1, min(GRID_H - 2, int(edge_r - drive_r * 3)))
spawn_px = spawn_tile_x * 32 + 16
spawn_py = spawn_tile_y * 32 + 16

# --- Decoration: matched against the aerial photo, which shows dense forest
# along the riverbank/island, a mown clearing right around the house/pool,
# and lighter tree cover through the rest of the park. Zones are defined by
# real distance (to water, to the house) rather than row/col ranges, so they
# hold up under any grid rotation. ---
def h(x, y, salt):
    return (x * 92821 + y * 68917 + salt) % 1000

CLEARING_RADIUS = 15
PARK_RADIUS = 48
RIVERBANK_BAND = 6

for r in range(GRID_H):
    for c in range(GRID_W):
        if ground[r][c] != GRASS or building[r][c] is not None:
            continue
        dist_house = math.hypot(r - house_cr, c - house_cc)
        if dist_house < CLEARING_RADIUS:
            continue  # mown clearing right around the house/pool
        is_riverbank = dist_to_water[r][c] is not None and dist_to_water[r][c] <= RIVERBANK_BAND
        is_park_zone = dist_house < PARK_RADIUS
        if not (is_riverbank or is_park_zone):
            continue
        # h() returns 0-999; these are out of 1000, not 100
        density = 620 if is_riverbank else 260
        v = h(c, r, 7)
        if v < density:
            building[r][c] = TREE if v % 2 == 0 else TREE2
        elif v < density + 120:
            building[r][c] = BUSH_A if v % 2 == 0 else BUSH_B

# --- Garden loop path near the pool, matching the oval walking path visible
# in the aerial photo, offset to the park side (away from the main house) ---
LOOP_CELLS = set()
if POOL_HOUSE:
    ph_cr, ph_cc = centroid(POOL_HOUSE)
    loop_cr = ph_cr + away_r * 20
    loop_cc = ph_cc + away_c * 20
    loop_rx, loop_ry = 10, 10
    for deg in range(0, 360, 2):
        rad = math.radians(deg)
        lc = int(loop_cc + loop_rx * math.cos(rad))
        lr = int(loop_cr + loop_ry * math.sin(rad))
        for orx in (-1, 0, 1):
            for ory in (-1, 0, 1):
                rr, cc2 = lr + ory, lc + orx
                if 0 <= rr < GRID_H and 0 <= cc2 < GRID_W and ground[rr][cc2] == GRASS:
                    ground[rr][cc2] = PATH
                    building[rr][cc2] = None
                    LOOP_CELLS.add((cc2, rr))

# hedges bordering the tennis court
for c in range(tcx - 7, tcx + 8):
    for r in (tcy - 5, tcy + 5):
        if 0 <= r < GRID_H and 0 <= c < GRID_W and ground[r][c] == GRASS and building[r][c] is None:
            building[r][c] = BUSH_A if (c % 2 == 0) else BUSH_B

# a couple of flowers by the house forecourt, either side of the driveway
if MAIN_HOUSE:
    for sign in (-1, 1):
        r = int(house_edge_r + drive_r * 3 + perp_r * 6 * sign)
        c = int(house_edge_c + drive_c * 3 + perp_c * 6 * sign)
        if 0 <= r < GRID_H and 0 <= c < GRID_W and ground[r][c] == GRASS:
            building[r][c] = FLOWER

# ---------------------------------------------------------------------------
# Export: autotiled, layered Tiled map (see retile.py)
#
# `ground` and `building` above still hold the old flat one-tile-per-terrain
# classification. Everything below re-expresses that as nine-sliced terrain on
# layered output, so boundaries get real corner/edge tiles instead of a hard
# 32px staircase.
# ---------------------------------------------------------------------------
import retile

IDX = retile.load_index()
NS = IDX['nine_slice']
STAMPS = IDX['stamps']
SINGLES = IDX['singles']

# Old-scheme ids -> new nine-slice terrain names
WATERY = {WATER, POOL}
PATHY = {PATH}

cells = lambda pred: {(x, y) for y in range(GRID_H) for x in range(GRID_W) if pred(ground[y][x])}

water_mask = cells(lambda t: t in WATERY)
# Real road/track/footway geometry from OSM, on top of the generated driveway.
path_mask = (cells(lambda t: t in PATHY)
             | OSM['road'] | OSM['track'] | OSM['footway']) - water_mask
earth_mask = cells(lambda t: t == ROOF_FILL)
court_mask = cells(lambda t: t == TENNIS)

# --- The island, and the bridge to it ---------------------------------------
# The estate's defining feature: L'Huisne splits and rejoins around a wooded
# island, reached by a bridge from just above the main house. Neither source
# has that bridge mapped, but the island falls straight out of the water union
# as an enclosed land component, and the crossing is then a geometry problem
# rather than something to place by hand.
def _enclosed_components(water):
    seen, comps = set(), []
    for yy in range(GRID_H):
        for xx in range(GRID_W):
            if (xx, yy) in water or (xx, yy) in seen:
                continue
            q = deque([(xx, yy)]); seen.add((xx, yy)); group = []; touches_edge = False
            while q:
                cx, cy = q.popleft(); group.append((cx, cy))
                if cx in (0, GRID_W - 1) or cy in (0, GRID_H - 1):
                    touches_edge = True
                for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                    n = (cx + dx, cy + dy)
                    if (0 <= n[0] < GRID_W and 0 <= n[1] < GRID_H
                            and n not in water and n not in seen):
                        seen.add(n); q.append(n)
            comps.append((group, touches_edge))
    return comps

_comps = _enclosed_components(water_mask)
_islands = [g for g, edge in _comps if not edge and len(g) >= 50]
_mainland = set(max((g for g, edge in _comps if edge), key=len, default=[]))
ISLAND = set(max(_islands, key=len)) if _islands else set()

BRIDGE_CELLS, BRIDGE_DECK = set(), set()
if ISLAND and MAIN_HOUSE:
    hr, hc = centroid(MAIN_HOUSE)
    house_xy = (hc, hr)
    # Straight water crossings from the island to the mainland, shortest span
    # closest to the house wins -- that is where a bridge would actually be.
    options = []
    for (ix, iy) in ISLAND:
        for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            x, y, span = ix + dx, iy + dy, 0
            while 0 <= x < GRID_W and 0 <= y < GRID_H and (x, y) in water_mask and span < 20:
                x += dx; y += dy; span += 1
            # span >= 3: a one- or two-tile gap is a rasterisation pinch where the
            # two channels nearly touch, not a channel anyone would bridge.
            # The landing must also sit ABOVE the house -- the causeway in the
            # aerial runs off the back of the building, and scoring on distance
            # alone kept picking a crossing on the near side instead.
            house_top = bbox(MAIN_HOUSE)[0]
            if (3 <= span and 0 <= x < GRID_W and 0 <= y < GRID_H
                    and (x, y) in _mainland and y < house_top - 1):
                d = math.hypot(x - house_xy[0], y - house_xy[1])
                if d <= 14:
                    # Among crossings near the house, prefer the widest channel:
                    # a 3-tile span reads as a box sitting on the bank rather
                    # than a bridge over water.
                    options.append((-span, round(d), (ix, iy), (x, y), (dx, dy)))
    if options:
        options.sort()
        options = [(b, -a, c, d_, e) for (a, b, c, d_, e) in options]
        _, span, (ix, iy), (mx, my), (dx, dy) = options[0]
        x0, x1 = min(ix, mx), max(ix, mx)
        y0, y1 = min(iy, my), max(iy, my)
        if dy == 0:                      # horizontal crossing
            for x in range(x0, x1 + 1):
                BRIDGE_DECK.add((x, y0))
                BRIDGE_CELLS.update({(x, y0 - 1), (x, y0), (x, y0 + 1)})
        else:                            # vertical crossing
            for y in range(y0, y1 + 1):
                BRIDGE_DECK.add((x0, y))
                BRIDGE_CELLS.update({(x0 - 1, y), (x0, y), (x0 + 1, y)})
        print(f"island: {len(ISLAND)} cells; bridge spans {span} water tiles "
              f"from island({ix},{iy}) to mainland({mx},{my})")
    else:
        print(f"island: {len(ISLAND)} cells but no straight crossing found")
else:
    print("island: none detected")

# A shallow margin one tile wide around every waterbody. Without it, deep water
# butts straight up against grass and the river reads as a blue staircase no
# matter how good the autotiling is -- the transition IS the shoreline.
shore = set()
for (wx, wy) in water_mask:
    for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1), (1, 1), (1, -1), (-1, 1), (-1, -1)):
        n = (wx + dx, wy + dy)
        if (0 <= n[0] < GRID_W and 0 <= n[1] < GRID_H
                and n not in water_mask and n not in path_mask):
            shore.add(n)

ground2 = {}
# shallow first across water+shore so the rim autotiles against grass, then
# deep water painted over the top of it
ground2.update(retile.autotile(water_mask | shore, GRID_W, GRID_H, NS['shallow']))
ground2.update(retile.autotile(water_mask, GRID_W, GRID_H, NS['water']))
ground2.update(retile.autotile(path_mask, GRID_W, GRID_H, NS['path']))
ground2.update(retile.autotile(earth_mask, GRID_W, GRID_H, NS['gravel']))
ground2.update(retile.autotile(court_mask, GRID_W, GRID_H, NS['clay']))

# Ground1 is an opaque grass bed under everything; Ground2 paints over it.
grass_c = NS['grass'][retile.C]
light_c = IDX['derived']['grass_light']
dark_c = IDX['derived']['grass_dark']

# Two grass tones in soft patches rather than one flat green. Two coarse octaves
# of the existing deterministic hash give irregular blobs; a single fine-grained
# sprinkle just looks like noise, and a single octave looks like tiling.
def _hash2(x, y, salt):
    """Proper integer hash in [0,1).

    build_map's existing h() is (x*92821 + y*68917 + salt) % 1000 -- linear in
    both axes, so sampling it on a lattice produced regular diagonal banding
    rather than noise, and the grass came out visibly striped. Keep h() for the
    scatter (changing it would reshuffle every tree) and mix properly here.
    """
    n = (x * 0x1f1f1f1f) ^ (y * 0x27d4eb2d) ^ (salt * 0x165667b1)
    n &= 0xFFFFFFFF
    n = (n ^ (n >> 15)) * 0x2545F491
    n &= 0xFFFFFFFF
    n = (n ^ (n >> 13)) * 0x3ad8025b
    n &= 0xFFFFFFFF
    return ((n ^ (n >> 16)) & 0xFFFF) / 65536.0


def _vnoise(x, y, scale, salt):
    """Value noise on a lattice of `scale`, smoothstep-interpolated.

    Thresholding h(x // scale, ...) directly gives hard rectangular blocks --
    which is exactly what the first attempt at grass patches looked like.
    Interpolating between lattice corners gives organic blobs instead.
    """
    gx, gy = x / scale, y / scale
    x0, y0 = int(gx // 1), int(gy // 1)
    fx, fy = gx - x0, gy - y0
    sx, sy = fx * fx * (3 - 2 * fx), fy * fy * (3 - 2 * fy)
    c = lambda ax, ay: _hash2(ax, ay, salt)
    top = c(x0, y0) * (1 - sx) + c(x0 + 1, y0) * sx
    bot = c(x0, y0 + 1) * (1 - sx) + c(x0 + 1, y0 + 1) * sx
    return top * (1 - sy) + bot * sy


ground1 = {}
for y in range(GRID_H):
    for x in range(GRID_W):
        # two octaves: broad drifts of mowing plus a finer break-up
        n = _vnoise(x, y, 11, 7717) * 0.6 + _vnoise(x, y, 4, 7919) * 0.4
        ground1[(x, y)] = dark_c if n < 0.36 else (light_c if n > 0.64 else grass_c)

# --- Trees: the old scatter placed single 32px tiles; promote them to the 2x2
# stamps that give the map its depth (upper half draws over the player).
occupied = set(water_mask) | set(path_mask)
deco, above = {}, {}
TREE_KINDS = ['tree_leafy', 'tree_round', 'tree_broad', 'tree_leafy', 'tree_round']

tree_spots, bush_spots = [], []
for y in range(GRID_H):
    for x in range(GRID_W):
        b = building[y][x]
        if b in (TREE, TREE2):
            tree_spots.append((x, y))
        elif b in (BUSH_A, BUSH_B):
            bush_spots.append((x, y))

# The old pass scattered single tiles at uniform density, which reads as an
# orchard rather than woodland. Grow a small cluster around each seed so the
# canopies touch and form masses, and jitter kind per-stamp for variety.
clustered = []
for (sx, sy) in tree_spots:
    # Thin the seeds hard. The upstream pass scatters at a uniform high density
    # which covers lawn and parkland alike; keeping roughly a third and letting
    # the survivors cluster gives open ground with wooded masses instead.
    if h(sx, sy, 8821) % 100 >= 34:
        continue
    # OSM says these are meadow -- mown, grazed, open. Trees there is exactly
    # the kind of invented detail the aerial-guessing pass kept producing.
    if (sx, sy) in OSM['meadow']:
        continue
    clustered.append((sx, sy))
    extra = h(sx, sy, 5501) % 3          # 0-2 companions per seed
    for k in range(extra):
        dx = (h(sx, sy, 6600 + k) % 5) - 2
        dy = (h(sx, sy, 7700 + k) % 5) - 2
        clustered.append((sx + dx, sy + dy))

SPECIMENS = ['specimen_oak', 'specimen_willow', 'specimen_oak2', 'specimen_willow2']
tree_trunks = set()

# Seeds that survived thinning and stand clear of their neighbours become mature
# specimens; the rest stay small and read as the scrubby mass behind them. That
# size hierarchy is what makes parkland look like parkland instead of an orchard.
# Crowding must be measured against the surviving spots, not the raw upstream
# scatter -- that set is dense almost everywhere, so testing against it rejected
# 863 of 879 candidates and no specimen ever got placed.
placed_set = set(clustered)
for spot in clustered:
    sx, sy = spot
    crowded = sum(1 for dx in range(-2, 3) for dy in range(-2, 3)
                  if (sx + dx, sy + dy) in placed_set) > 3
    # Wide enough that the 3x4 footprint can still sit clear of the bank. At
    # radius 3 the stamp always overlapped water and every willow was rejected.
    near_water = any((sx + dx, sy + dy) in water_mask
                     for dx in range(-7, 8) for dy in range(-7, 8))
    if not crowded and h(sx, sy, 2207) % 100 < 55:
        # willows by the water, oaks out on the grass
        pool = SPECIMENS[1::2] if near_water else SPECIMENS[0::2]
        kind = pool[h(sx, sy, 3313) % len(pool)]
    else:
        kind = TREE_KINDS[h(sx, sy, 3313) % len(TREE_KINDS)]
    lo, up, tr = retile.place_stamps([spot], STAMPS[kind], GRID_W, GRID_H, occupied)
    deco.update(lo)
    above.update(up)
    tree_trunks |= tr

# Hedgerows on the real field boundaries. This corner of the Sarthe is bocage
# country -- fields are defined by their hedges -- and OSM gives the actual
# edges. Autotiling the meadow set with the hedge block and then discarding the
# centre tile leaves exactly the border ring: hedge segments that turn corners
# correctly, rather than a line of identical bushes.
hedge_ids = NS['hedge']
hedge_centre = hedge_ids[retile.C]
# The bocage hedges sit out in the farmland, mostly beyond the crop. The estate
# core is parkland, so the hedges that actually show are the clipped ones an
# estate really has: enclosing the tennis court and the pool terrace.
def _dilate(cells, r):
    out = set()
    for (cx, cy) in cells:
        for dx in range(-r, r + 1):
            for dy in range(-r, r + 1):
                out.add((cx + dx, cy + dy))
    return out

# Only the court and the pool terrace get clipped hedges. Dilating every
# roof-fill footprint ringed each shed and outbuilding in box hedge, which
# looked like topiary run amok rather than an estate.
pool_cells = cells(lambda t: t == POOL)
enclosures = set()
for region in (court_mask, pool_cells):
    if region:
        enclosures |= _dilate(region, 2) - _dilate(region, 1)

meadow_cells = {c for c in (OSM['meadow'] | enclosures)
                if c not in water_mask and c not in path_mask and c not in occupied
                and 0 <= c[0] < GRID_W and 0 <= c[1] < GRID_H}
hedges = {c: t for c, t in retile.autotile(meadow_cells, GRID_W, GRID_H, hedge_ids).items()
          if t != hedge_centre}
deco.update(hedges)
occupied |= set(hedges)
hedge_cells = set(hedges)

# Avenue planting. A lime avenue flanking the approach is the defining feature
# of a French estate drive, and it gives the parkland the linear structure that
# open lawn alone cannot -- the eye follows it to the house.
avenue = []
for (px_, py_) in sorted(path_mask):
    for dx, dy in ((2, 0), (-2, 0), (0, 2), (0, -2)):
        cell = (px_ + dx, py_ + dy)
        mid = (px_ + dx // 2, py_ + dy // 2)
        if (cell in occupied or cell in path_mask or mid in path_mask
                or cell in water_mask or cell in LOOP_CELLS):
            continue
        if not (0 <= cell[0] < GRID_W and 0 <= cell[1] < GRID_H):
            continue
        # every few tiles along the drive, so the trees read as a planted rhythm
        if (px_ + py_) % 5 == 0 and _hash2(cell[0], cell[1], 4801) < 0.55:
            avenue.append(cell)

for cell in avenue:
    kind = SPECIMENS[_hash2(cell[0], cell[1], 991) > 0.5 and 2 or 0]
    lo, up, tr = retile.place_stamps([cell], STAMPS[kind], GRID_W, GRID_H, occupied)
    deco.update(lo)
    above.update(up)
    tree_trunks |= tr

lo, up, tr = retile.place_stamps(bush_spots, STAMPS['bush_small'], GRID_W, GRID_H, occupied)
deco.update(lo)
above.update(up)
tree_trunks |= tr

# --- Buildings: stretch a manor block across each real cadastral footprint.
# The footprints are accurate (the main house is 12 tiles wide), so a fixed
# house sprite can't fit them -- see retile.stretch_building.
building_cells = {}
building_above = {}
MANOR = IDX['h_stretch']['manor']
COTTAGES = [IDX['buildings']['cottage_red'], IDX['buildings']['cottage_green']]

# Every real footprint becomes a building filling its own bbox. Previously
# anything under 5 cells was skipped and larger ones only got a 3-row stamp,
# so the cadastral roof-fill showed through as grey slabs around the yard.
for i, comp in enumerate(sorted(buildings, key=len, reverse=True)):
    if len(comp) < 3:
        continue                      # cadastral noise, not a structure
    r0, r1, c0, c1 = bbox(comp)
    width, depth = c1 - c0 + 1, r1 - r0 + 1
    # Cadastral footprints are ragged 2.5 m rasterisations. Drawing them
    # literally gives orange amoebas; filling their bounding box gives slabs.
    # Real buildings are rectangular, so fit a clean rectangle of the right area
    # at the footprint's centre and draw that.
    if len(comp) >= 12:
        fill_ratio = len(comp) / float(width * depth)
        if fill_ratio < 0.75:
            aspect = width / float(depth)
            fit_d = max(2, int(round(math.sqrt(len(comp) / aspect))))
            fit_w = max(2, int(round(len(comp) / float(fit_d))))
            width, depth = min(width, fit_w), min(depth, fit_d)
        cr_, cc_ = centroid(comp)
        c0 = max(0, min(GRID_W - width, int(cc_ - width / 2)))
        r0 = max(0, min(GRID_H - depth, int(cr_ - depth / 2)))
        roof = ['manor', 'manor_slate', 'manor_brown', 'manor_slate'][
            h(c0, r0, 8123) % 4]
        lo, up = retile.stretch_building_2d(IDX['h_stretch'][roof], c0, r0, width, depth)
    else:
        spec = COTTAGES[h(c0, r0, 4409) % len(COTTAGES)]
        cy = max(0, r1 - spec['h'] + 1)
        lo, up = {}, {}
        for dy in range(spec['h']):
            for dx in range(min(spec['w'], width)):
                cell = (c0 + dx, cy + dy)
                if 0 <= cell[0] < GRID_W and 0 <= cell[1] < GRID_H:
                    (up if dy == 0 else lo)[cell] = spec['ids'][dy][dx]

    building_cells.update(lo)
    building_above.update(up)

above.update(building_above)
deco.update(building_cells)

# --- Garden furniture -------------------------------------------------------
# Beds flanking the forecourt, benches and lamps set just off the carriage loop.
# Placed against real features rather than scattered, so they read as deliberate.
props = {}
_loop = sorted(LOOP_CELLS)
for i, cell in enumerate(_loop):
    if cell in occupied or cell in path_mask:
        continue
    n = h(cell[0], cell[1], 9311) % 100
    if n < 4:
        props[cell] = SINGLES['bench']
    elif n < 6:
        props[cell] = SINGLES['lamp']

if MAIN_HOUSE:
    _hr0, _hr1, _hc0, _hc1 = bbox(MAIN_HOUSE)
    for i, cx in enumerate(range(_hc0, _hc1 + 1, 3)):
        for cy in (_hr1 + 2, _hr1 + 3):
            cell = (cx, cy)
            if (0 <= cx < GRID_W and 0 <= cy < GRID_H
                    and cell not in occupied and cell not in path_mask
                    and cell not in water_mask):
                props[cell] = SINGLES['bed_blue' if i % 2 else 'bed_pink']

deco.update(props)
occupied |= set(props)

# --- Bridge to the island ---
# stretch_building puts row 0 on the Above layer, which is exactly right here:
# the player walks along the deck and passes *behind* the far parapet.
bridge_deck_cells = set()
if BRIDGE_DECK:
    _bx = sorted({x for x, _ in BRIDGE_DECK})
    _by = sorted({y for _, y in BRIDGE_DECK})
    if len(_bx) >= len(_by):                       # horizontal crossing
        lo, up = retile.stretch_building(IDX['h_stretch']['bridge'],
                                         _bx[0], _by[0] - 1, len(_bx))
    else:                                          # vertical: no rotated art in
        lo, up = {}, {}                            # the sheet, so lay a path instead
        for (x, y) in BRIDGE_DECK:
            lo[(x, y)] = NS['gravel'][retile.C]
    deco.update(lo)
    above.update(up)
    bridge_deck_cells = set(BRIDGE_DECK)

    # The bridge lands beside the house and its abutment overlaps the footprint;
    # re-apply the buildings so the manor wins that overlap rather than having a
    # parapet drawn through its wall.
    deco.update(building_cells)
    above.update(building_above)
    bridge_deck_cells -= set(building_cells) | set(building_above)

# Trees are placed before buildings, so `occupied` could not know about them and
# a canopy could land on a roof. Buildings win their own footprint on both
# layers; without the Above sweep a canopy still drew over the roof body.
_bcells = set(building_cells) | set(building_above)
above = {k: v for k, v in above.items() if k not in _bcells or k in building_above}
deco = {k: v for k, v in deco.items() if k not in _bcells or k in building_cells}
deco.update(building_cells)
above.update(building_above)
tree_trunks -= _bcells

# --- Collision: one invisible marker tile, far easier to author than
# per-tile properties on a shared tileset.
COLLIDE_ID = IDX['tilecount'] - 1
solid = set(water_mask) | tree_trunks | hedge_cells | set(building_cells) | set(building_above)
# The whole point of a bridge is that the water under it stops being solid.
# Parapets stay solid, so you can't walk off the side.
solid -= bridge_deck_cells
collision = {c: COLLIDE_ID for c in solid}

# Crop to the dense core. The full 132x132 plan is mostly empty parkland, which
# is exactly why the old map read as a speck in a field.
# Anchor the crop on the main house and pool house only. The gatehouse sits ~33
# tiles away at the road, and including it drags the crop back out to most of
# the plan -- which is the emptiness we're trying to cut.
core_anchor = {}
for comp in (MAIN_HOUSE, POOL_HOUSE):
    if comp:
        for (r, c) in comp:
            core_anchor[(c, r)] = 1
# Anchor on the whole estate, not just the main house: the carriage loop, the
# tennis court and every outbuilding. Framing on the house alone cropped half
# the loop away and left far less ground to walk on than the place actually has.
for cell in LOOP_CELLS:
    core_anchor[cell] = 1
for cell in court_mask:
    core_anchor[cell] = 1
for comp in buildings:
    if len(comp) >= 3:
        for (r, c) in comp:
            core_anchor[(c, r)] = 1

_layers = {'Ground1': ground1, 'Ground2': ground2, 'Deco': deco,
           'Above': above, 'CollisionLayer': collision, 'CoreAnchor': core_anchor,
           'PathMask': {c: 1 for c in path_mask}}
_layers, (spawn_px, spawn_py), CROP_X, CROP_Y, GRID_W, GRID_H = retile.crop_layers(
    _layers, (spawn_px, spawn_py), GRID_W, GRID_H, pad=10, anchor=('CoreAnchor',))
_layers.pop('CoreAnchor')
_path_cropped = _layers.pop('PathMask')

# The upstream spawn sits at the road, which the crop cuts away -- clamping it
# leaves the player wedged in a map corner. Re-seat it on the driveway nearest
# the middle of the core instead, so you start on the approach to the house.
_solid = _layers['CollisionLayer']
_cx, _cy = GRID_W / 2, GRID_H / 2
_walkable = [c for c in _path_cropped if c not in _solid]
if _walkable:
    _sx, _sy = min(_walkable, key=lambda c: (c[0] - _cx) ** 2 + (c[1] - _cy) ** 2)
    spawn_px, spawn_py = _sx * 32 + 16, _sy * 32 + 16
    print(f"spawn re-seated on driveway at tile ({_sx},{_sy})")

# Ground1 is the opaque bed: refill any cell the crop left bare.
grass_bed = _layers['Ground1']
for y in range(GRID_H):
    for x in range(GRID_W):
        grass_bed.setdefault((x, y), grass_c)

print(f"cropped to {GRID_W}x{GRID_H} at offset ({CROP_X},{CROP_Y})")

layers_out = [(name, retile.flatten(_layers[name], GRID_W, GRID_H))
              for name in ('Ground1', 'Ground2', 'Deco', 'Above', 'CollisionLayer')]

tilemap = {
    "compressionlevel": -1,
    "width": GRID_W, "height": GRID_H,
    "tilewidth": 32, "tileheight": 32,
    "infinite": False, "orientation": "orthogonal", "renderorder": "right-down",
    "type": "map", "version": "1.10", "tiledversion": "1.10.2",
    # Published so the scene never has to hardcode it: the marker's gid moves
    # whenever the tileset grows, and a stale constant fails silently as
    # "collision just stopped working".
    "properties": [{"name": "collisionGid", "type": "int", "value": COLLIDE_ID + 1}],
    "nextlayerid": len(layers_out) + 2, "nextobjectid": 2,
    "layers": [
        {"id": i + 1, "name": name, "type": "tilelayer", "visible": name != 'CollisionLayer',
         "opacity": 1, "x": 0, "y": 0, "width": GRID_W, "height": GRID_H, "data": data}
        for i, (name, data) in enumerate(layers_out)
    ] + [
        {"id": len(layers_out) + 1, "name": "Objects", "type": "objectgroup",
         "visible": True, "opacity": 1, "x": 0, "y": 0, "draworder": "topdown",
         "objects": [{"id": 1, "name": "Spawn Point", "type": "", "rotation": 0,
                      "visible": True, "x": spawn_px, "y": spawn_py, "width": 0, "height": 0}]}
    ],
    "tilesets": [
        {"firstgid": 1, "name": "avz_tileset", "image": "tileset.png",
         "imagewidth": IDX['imagewidth'], "imageheight": IDX['imageheight'],
         "tilewidth": 32, "tileheight": 32,
         "columns": IDX['columns'], "tilecount": IDX['tilecount'],
         "margin": 0, "spacing": 0, "tiles": []}
    ],
}

out_path = os.path.join(_HERE, '..', '..', 'assets', 'avz', 'avz-map.json')
with open(out_path, "w") as f:
    json.dump(tilemap, f)

print("wrote", out_path)
print("grid", GRID_W, "x", GRID_H)
for name, data in layers_out:
    print(f"  {name:<16} nonzero={sum(1 for v in data if v):<6} distinct={len({v for v in data if v})}")
